In [14]:
import numpy as np
myarr = np.array([1,2,200,4,5], np.int8)
myarr

array([  1,   2, -56,   4,   5], dtype=int8)

In [15]:
myarr.dtype

dtype('int8')

In [20]:
linspace = np.linspace(1, 15, 15)
linspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [24]:
identity = np.identity(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
array = np.array([1,2,3,4,5,6,7,8,9])
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
array
reshape = array.reshape(3,3)
reshape

reshape.sum(axis=0)



array([12, 15, 18])

In [46]:
array2 = np.arange(16)
array2 = array2.reshape(4,4)
print(array2)
array2.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 6, 22, 38, 54])

In [50]:
array2 = np.arange(16)
array2 = array2.reshape(4,4)
array2 = array2.T
print("Transpose Array : \n",array2)


Transpose Array : 
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [53]:
array2 = np.arange(16)
array2 = array2.reshape(4,4)
array2 = array2.flat
print("Transpose Array : \n",array2)

for i in array2:
    print(i,end=" ")

Transpose Array : 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [57]:
array2 = np.arange(16)
array2 = array2.reshape(4,4)

for i in array2.flat:
    print(i,end=" ")
print("\nDimention Of Array: ",array2.ndim)
print("\nTotal size Occupie Of Array: ",array2.nbytes)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 
Dimention Of Array:  2

Total size Occupie Of Array:  64


In [64]:
ar = np.arange(9)
ar = ar.reshape(3,3)
print(ar)
ar = ar.argmax()
print("Array Of Max Index : ",ar)

ar = ar.argmin()
print("Array Of Min Index : ",ar)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array Of Max Index :  8
Array Of Min Index :  0


In [70]:
ar = np.array([[1,4,2],[7,3,6],[2,4,9]])
print(ar)
ar = ar.argmax(axis=0)
print("Array Of Max Index : ",ar)


[[1 4 2]
 [7 3 6]
 [2 4 9]]
Array Of Max Index :  [1 0 2]


In [71]:
ar = np.array([[1,4,2],[7,3,6],[2,4,9]])
print(ar)
ar = ar.argmin(axis=0)
print("Array Of Max Index : ",ar)


[[1 4 2]
 [7 3 6]
 [2 4 9]]
Array Of Max Index :  [0 1 0]


In [74]:
ar = np.array([[1,4,2],[7,3,6],[2,4,9]])

ar.argsort(axis=1)

array([[0, 2, 1],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [75]:
ar.ravel()

array([1, 4, 2, 7, 3, 6, 2, 4, 9])

In [77]:
ar.reshape(3,3)

array([[1, 4, 2],
       [7, 3, 6],
       [2, 4, 9]])

In [8]:
import sys
import numpy as np


py_arr = [1,2,3,4,5]
# py_arr = [1,2]
np_arr = np.array(py_arr)

print("Python Size:",sys.getsizeof(1) * len(py_arr))
print("Numpy Size : ",np_arr.itemsize * np_arr.size)

Python Size: 140
Numpy Size :  20
