In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr.ndim   #gives dimension

1

In [10]:
arr.size  #gives size of array

4

In [11]:
arr.shape

(4,)

In [12]:
arr_2d=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(arr_2d)
print(type(arr_2d))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>


In [13]:
arr_2d.ndim

2

In [14]:
arr_2d.size

12

In [15]:
arr_2d.shape

(3, 4)

In [16]:
arr_md=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[5,6,7,8],[5,6,7,8],[5,6,7,8],[5,6,7,8]],[[1,3,5,7],[1,3,5,7],[1,3,5,7],[1,3,5,7]]])
print(arr_md)
print(type(arr_md))

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]]

 [[1 3 5 7]
  [1 3 5 7]
  [1 3 5 7]
  [1 3 5 7]]]
<class 'numpy.ndarray'>


In [17]:
arr_md.size

48

In [18]:
arr_md.shape

(3, 4, 4)

In [19]:
arr_md.ndim

3

In [24]:
arr_1=np.ones((5,5),dtype=int)  # bydefault float value accepted
print(arr_1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
arr_0=np.zeros((5,5),dtype=int)  # bydefault float
print(arr_0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [27]:
arr_1=np.ones((5,5),dtype=bool)  # bydefault float value accepted
print(arr_1)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [ ]:
# ones
# zeros
# empty
# arange
# arange(start,end,step)

In [28]:
e=np.eye(3)  # for creating identical matrix
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
x=np.empty((5,5))  #random values #bydefault floating values
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
x=np.empty((5,5),dtype=int)  #random values #bydefault floating values
x

array([[        50,         48,         50,         51,         45],
       [        48,         50,         45,         48,         51],
       [        84,         48,         53,         58,         49],
       [        56,         58,         50,         54,         46],
       [        52,         50,         53,         90, 1714764081]])

In [43]:
f=np.full((5,5),4.2)         #fill whole array with specific value
f

array([[4.2, 4.2, 4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2, 4.2, 4.2]])

In [44]:
f=np.full((2,5,5),4.78)         #fill whole array with specific value
f

array([[[4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78]],

       [[4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78],
        [4.78, 4.78, 4.78, 4.78, 4.78]]])

In [50]:
from numpy import random

i=np.random.randint(70,size=30)  # 70 denote lat value
i

array([35, 34, 44, 42, 38, 10,  1, 42, 38,  4, 51, 36, 59, 16, 62, 23, 58,
       34, 66, 18, 32, 18, 57, 56, 30, 10, 19, 17, 47,  9])

In [59]:
x=[35,65,76,43,75,32,89]

random.choice(x)  

32

In [60]:
y=[35,65,76,43,75,32,89]

random.choice(y,size=30)  

array([43, 32, 76, 76, 32, 65, 43, 35, 43, 35, 43, 35, 65, 43, 75, 35, 89,
       35, 89, 32, 76, 32, 43, 89, 76, 76, 32, 76, 32, 89])

In [67]:
t=random.rand(5,5)
t

array([[0.95798978, 0.20423619, 0.19104971, 0.52776688, 0.80154265],
       [0.7804584 , 0.90495621, 0.25971451, 0.53347214, 0.12309354],
       [0.7751399 , 0.57574346, 0.56584336, 0.27386524, 0.04028968],
       [0.39540378, 0.80354226, 0.19472656, 0.03897703, 0.83026833],
       [0.99818325, 0.28358608, 0.4757365 , 0.00396626, 0.00106614]])

In [85]:
# seed function generate constant random values

random.seed(10)
t=random.rand(5,5)
t

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317]])

In [87]:
j=np.random.ranf(70)  # 70 denote lat value
j

array([0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895,
       0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935,
       0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715,
       0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264,
       0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ,
       0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445,
       0.94426071, 0.98762547, 0.45630455, 0.82612284, 0.25137413,
       0.59737165, 0.90283176, 0.53455795, 0.59020136, 0.03928177,
       0.35718176, 0.07961309, 0.30545992, 0.33071931, 0.7738303 ,
       0.03995921, 0.42949218, 0.31492687, 0.63649114, 0.34634715,
       0.04309736, 0.87991517, 0.76324059, 0.87809664, 0.41750914,
       0.60557756, 0.51346663, 0.59783665, 0.26221566, 0.30087131,
       0.02539978, 0.30306256, 0.24207588, 0.55757819, 0.56550702,
       0.47513225, 0.29279798, 0.06425106, 0.97881915, 0.33970784])

In [88]:
arr_2dd=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2dd)
print(type(arr_2d))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [89]:
arr_2dd.ndim

2

In [90]:
arr_2dd.shape

(3, 4)

In [97]:
print(arr_2dd[0])                 #indexing
print(arr_2dd[0][3])
print(arr_2dd[1])

[1 2 3 4]
4
[5 6 7 8]


In [99]:
#slicing

arr_2dd[0:3,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [101]:
arr_2dd[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [103]:
print(arr_2dd[0:3,0:1])
print(arr_2dd[1:3,1:3])  #goes to end-1

[[1]
 [5]
 [9]]
[[ 6  7]
 [10 11]]


In [106]:
arr=np.arange(1,13)              #goes up to end-1
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [112]:
arr1=np.arange(1,12,2)              #goes up to end-1
print(arr1)

[ 1  3  5  7  9 11]


In [113]:
#linspace()            work as arange but we want more value in definit range  with equal space in all the values

arr2=np.linspace(1,3,50)              #50 shows number of values  
print(arr2)

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]


In [ ]:
#arange function and linspace function always generates one dimensional array

In [115]:
arr3=arr2.reshape(5,10)
arr3

array([[1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
        1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694],
       [1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
        1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ],
       [1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
        2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347],
       [2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
        2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673],
       [2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
        2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ]])

In [116]:
# convert the multidimentional array in one dimensional  --ravel function

print(arr3.ravel())

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]


In [121]:
task=np.arange(1,21)
print(task)
print()



task1=task.reshape(4,5)
print(task1)
print()

print(task1[1:3,1:4])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 7  8  9]
 [12 13 14]]
